language: node_js
node_js:
  - "lts/*"
script: KARMA_OPTS="--browsers Firefox,PhantomJS" make -e test
before_script:
  - export DISPLAY=:99.0
services:
  - xvfb
addons:
  firefox: latest
script: KARMA_OPTS="--browsers Firefox" make -e test
